### ISSUE TITLE
A little fix concerning trailing separators

### ISSUE THREAD

**Issue by alexsawallich** [aubiplus/seo#2]
I saw your module on zfmodules.com and was curious what it does - so I read through the code.

I'm not able to make a pull-request at the moment. So I want to provide a small correction here....

In Line 56 of your `Aubiplus\Seo\Service\Url` you write:

    $string = trim($string, '-');

However this should be

    $string = trim($string, $this->config->get('separator'));

Cheers and happy coding,
Alex

**Comment by FabianKoestring** [comment]
Hey @alexsawallich ,

it`s just a module to make nice readable urls. 

What do you mean with
> I'm not able to make a pull-request at the moment

Do you mean you cant create a pull request because of repository settings or you havent time at the moment?
Nevertheless you are right. It should be `$this->config->get('separator')`.

**Comment by alexsawallich** [comment]
@FabianKoestring I am at the office now, where I haven't setup a git-client. So I would have to wait till tonight to make a pull-request. But since it was such a little obvious fix I wrote it down here :)

**Comment by FabianKoestring** [comment]
Ok thanks, thought i had wrong settings in repository.
